### ISSUE TITLE
We ought to have our own colour palette for pie charts

### ISSUE THREAD

**Issue by alexkalderimis** [intermine/im-tables#131]
In line with our main colour palette, with the possibility to generate it from the less variables would be awesome.

**Comment by ArifaMujawar** [comment]
Hello I am outreachy applicant, I would like to work on this issue. Please can you help me to get started

**Comment by yochannah** [comment]
hey @ArifaMujawar! 

I would suggest setting a bunch of less variables somewhere that is easy to edit/update (head of file or a separate file maybe) and making them work for the pie charts in the column summaries.

you can take colours from the InterMine website - see here - https://github.com/intermine/intermine-homepage-2017/blob/master/static/style.less#L9-L14 

Pie charts are a type of column summary - you can learn more about them here: https://flymine.readthedocs.io/en/latest/results-tables/Documentationresultstables.html#column-summaries 

If you have trouble finding the pie chart code in the code base let us know!

**Comment by yochannah** [comment]
oh - I'd suggest looking through the templates tab on flymine to try to find an example of a pie chart column summary. if you look for a bit and can't find an example, we can help.

**Comment by ArifaMujawar** [comment]
could you please assign me this task.

**Comment by ArifaMujawar** [comment]
Thank you for your response @yochannah, I will clone the project and start figuring out the issue by myself. I will get back to you if I have any questions. 

Will I be assigned to this issue on github? Thanks

**Comment by heralden** [comment]
Fixed by #220
