### ISSUE TITLE
Cells that hold a URL value appear blank.

### ISSUE THREAD

**Issue by joshkh** [intermine/im-tables#154]
For example, this Flymine query returns Data Sets with their name and URL. The URL column either contains "NO VALUE" or a blank cell.

<query model="genomic" view="DataSet.name DataSet.url" sortOrder="DataSet.name ASC" >
  <constraint path="DataSet.url" op="ONE OF" >
    <value>http://redfly.ccr.buffalo.edu/?content=/search.php</value>
    <value>http://www.uniprot.org/</value>
  </constraint>
</query>

The column summaries still show the values.

**Comment by joshkh** [comment]
@sergiocontrino , can you test this on beta flymine?

**Comment by sergiocontrino** [comment]
perfect!

**Comment by sergiocontrino** [comment]
closing
