### ISSUE TITLE
Update error messages to be less chatty

### ISSUE THREAD

**Issue by yochannah** [intermine/im-tables#165]
From Gos: 

> can we avoid saying "Server error - our bad!"? It somehow comes across
> as if we aren't being serious. Maybe "Oops!" too, I'm not sure.

https://github.com/intermine/im-tables/blob/9b06e2892b36226f4ecb5d7dce7cfc9422d087ac/src/messages/error.coffee#L22

**Comment by Dhruvi16** [comment]
Hey! I would like to take this up!

**Comment by heralden** [comment]
@Dhruvi16 Great, I assigned it to you.
