### ISSUE TITLE
Upgrade very old node dependencies [coffeescript + node skills required]

### ISSUE THREAD

**Issue by yochannah** [intermine/im-tables#166]
im-tables builds on older versions of node like 0.10 and 0.12, but doesn't complete a build in modern versions of node. It would be much easier to update if it built correctly using more modern dependencies. Currently, I have to use [nvm](https://github.com/creationix/nvm) to roll back my node version to get this to build. 

### Task: 
Run npm update and perform code changes as needed to get the package to build successfully. `grunt test` needs to pass before any PR can be accepted. 

This is probably a non-trivial ticket that may require some time and thought. 

Comment on the issue if you're interested in picking this up! 

### What to do if you need help

The build steps can be inspected at https://github.com/intermine/im-tables/blob/master/Gruntfile.js -please also see our [contributing guidelines](https://github.com/intermine/im-tables/blob/master/CONTRIBUTING.md). 

If the docs don't answer your questions, mention @yochannah, tweet [@yoyehudi](http://www.twitter.com/yoyehudi), pop by to say hi on [chat](http://chat.intermine.org) or if needed email yo@intermine.org

**Comment by LakshSingla** [comment]
@yochannah I would like to work on this issue, along with working on `imjs` bit. :)

**Comment by yochannah** [comment]
@LakshSingla feel free to investigate this, but I think this should probably be a task that is part of the actualy GSoC project plan! :)

**Comment by yochannah** [comment]
This was fixed by @LakshSingla
