### ISSUE TITLE
Regression - Cells that hold a URL appear blank

### ISSUE THREAD

**Issue by yochannah** [intermine/im-tables#170]
See https://github.com/intermine/im-tables/issues/154 - there is a version of this code where this is fixed but I think it was only released on the CDN and never merged into the main codebase. 

@julie-sullivan Two options: 

1) if we roll back to version 2.0.0-beta we will be able to fix this bug, but re-introduce the bugs fixed in #157 and #159
2) I block off a chunk of time (length unknown) to figure out how to update im-tables to build. Could be a few hours, days, (hopefully not weeks)?

Preferences?

**Comment by julie-sullivan** [comment]
option 1 doesn't seem that great! option 2!

**Comment by yochannah** [comment]
note to self: try looking at the compiled but non-minified version in the CDN to see if it is easy to tell what the fix was.

**Comment by yochannah** [comment]
Fixed by #201
