### ISSUE TITLE
Fix styling of readme in Contributing guide.

### ISSUE THREAD

**Issue by CodHeK** [intermine/im-tables#171]
![screenshot 2019-03-07 at 2 46 30 pm](https://user-images.githubusercontent.com/22097366/53945574-ec719300-40e7-11e9-87a7-5b34a4713861.png)

I was looking to contribute to `im-tables` project found this contributing guide, on the first look the font sizes didn't seem to be readable ... I'd like to fix this for a start towards developing this project! @yochannah

**Comment by yochannah** [comment]
@CodHeK Please go ahead and fix this!!

**Comment by yochannah** [comment]
Hmmm, looking at the contributing file I think that it might be out of date - it was last updated in 2013! We also have https://github.com/intermine/im-tables/blob/master/DEVELOPING.md which *might* work better?

**Comment by CodHeK** [comment]
@yochannah should I merge the developing and contributing guide into just one... I think the contributing guide itself is enough and we can chuck the developing guide which I feel is redundant!

**Comment by yochannah** [comment]
Fixed by #172 - thanks so much @CodHeK !!
