### ISSUE TITLE
Migrate bower packages to npm

### ISSUE THREAD

**Issue by yochannah** [intermine/im-tables#187]
Bower is deprecated, but we have two dependencies managed by bower: https://github.com/intermine/im-tables/blob/dev/bower.json 

let's migrate these to npm instead and keep things simple.

**Comment by yochannah** [comment]
There are also a few bower related tasks in the gruntfile that will need to be removed or modified: https://github.com/intermine/im-tables/blob/dev/Gruntfile.js#L121

**Comment by jshreyans** [comment]
Hi @yochannah! I'm new to the codebase and would like to take up this issue.
I get the part about migrating to npm for all `mocha` and `chai` but can you explain what related tasks need to be modified in the gruntfile?

**Comment by yochannah** [comment]
@jshreyans Awesome, thansk for volunteering! 🚀 

for the gruntfile, I think just remove the bower install task (since it should be covered by npm now) 

here https://github.com/intermine/im-tables/blob/dev/Gruntfile.js#L111 and here https://github.com/intermine/im-tables/blob/dev/Gruntfile.js#L213

**Comment by jshreyans** [comment]
Great. I'll send a PR with the changes as soon as possible.

**Comment by jshreyans** [comment]
@yochannah I installed both `mocha` and `chai` with npm and the installation completed without any hiccups. However, I did get a considerable number of vulnerabilities. Any ideas about this?

**Comment by yochannah** [comment]
don't worry about the vulnerabilities for now - we're aware of them and likely the response will be a re-write of im-tables in the medium to longer term.

**Comment by jshreyans** [comment]
All right, thanks a lot. 
Also, I noticed that running `npm install` modified the `dist` folder in the project's directory. Is that a development build of the project?

**Comment by yochannah** [comment]
that is the prod build, I think.  it's a bit odd, isn't it? im-tables is old enough I tihnk it was set up before a lot of npm norms were establish - we probably wouldn't set it up this way these days!

**Comment by jshreyans** [comment]
Exactly my thoughts. It was really weird to see the series of commands executed on just an installation call.
So I've made the changes and will send a PR shortly.

**Comment by jshreyans** [comment]
@yochannah Are there any changes needed in the PR above?
