### ISSUE TITLE
Add basic unit tests

### ISSUE THREAD

**Issue by Manasa2850** [intermine/im-tables#224]
I would like to add unit tests which test if the package builds correctly and the table loads properly.
@yochannah could you please let me know if there are some specific tests you require
Thanks!

**Comment by yochannah** [comment]
@Manasa2850 thansk for volunteering to do this! What you've suggested above is already a massive improvement 💯  

if you have time for more tests,take a look through these two files: https://github.com/intermine/im-tables/tree/dev/test/release-testing
