### ISSUE TITLE
Add support for multi type constraints

### ISSUE THREAD

**Issue by alexkalderimis** [intermine/im-tables#34]
A test query is needed.

**Comment by Manasa2850** [comment]
@yochannah I would like to work on this. 
Could you please let me know what exactly the issue is?

**Comment by yochannah** [comment]
@Manasa2850 - I'll be honest, the issue is pretty sparse and I don't know what the aim of the game was here! 😆  let's close this one - the person who created the issue hasn't worked at InterMine for a while.
