### ISSUE TITLE
Result Cells: Subtable links pixel precision

### ISSUE THREAD

**Issue by radekstepan** [intermine/im-tables#41]
When a subtable has a value that breaks a line (in red), there is only a few (5px) of space to click if I want to get a preview box instead of visiting a Report page.

Perhaps collapse the blue border (in blue) and increase the padding of the inner `<td/>` (in yellow)?

![Screenshot - 260313 - 11:52:03](https://f.cloud.github.com/assets/195584/302631/9d6c783e-960b-11e2-9c07-17385151ff44.png)

**Comment by yochannah** [comment]
I don't think this applies to the current version any more.
