### ISSUE TITLE
List Management: tags interface slight box issues in IE9

### ISSUE THREAD

**Issue by radekstepan** [intermine/im-tables#48]
The blue highlighted box spreads outside and for subsequent links stretches all the way across the modal box.

![Screenshot - 260313 - 12:24:26](https://f.cloud.github.com/assets/195584/302721/22106650-9610-11e2-826b-8a75e0e7a467.png)

**Comment by yochannah** [comment]
something like 0.2% of flymine users still use IE9. Closing issue
