### ISSUE TITLE
keyword search for exact example times out when exact example is a gene symbol only

### ISSUE THREAD

**Issue by sierra-moxon** [intermine/im-tables#84]
Our experience has been that if the example text is an actual search that the user can do (we changed our example text to a real gene symbol with no other text -- no e.g, etc...), then entering that exact example gene symbol in a search will cause the search to be so slow that the browser times out.  All other searches work fast and well.  I tested this by changing the example text a few times.  Each time, whenever I entered the exact example text (I tried with two different gene symbols), the exact sample text search would be so slow the browser would time out, but all other searches were fine (including the previously slow example!).  

So, the two solutions we've found (so far) are: 
1) make the example text something no one should/would search for (i.e.: e.g: zen, …), or 
2) exclude the example text (this is what we did by removing quick search.identifiers and the other quicksearch web.properties parameter that controls the example text in the search box on the home page (in the middle section, as opposed to the top right).

I'm not sure if you have to re-index using the -Daction=create-search-index flag, it sounds like I didn't, but it was part of my process after changing the web.properties.  Then I re-released the web app to see the property changes, and re-seeded my search (since the first search is always slow). Without example text, I can search just fine with the problematic example.

My process:
1) change web.properties to set the example text for quicksearch both in the top right and in the middle section on the homepage to an exact gene symbol (popular exact gene symbol) with no other text in the example.
2) re-run the index  using -Daction=create-search-index
3) re-release the webapp using the ant target
4) re-seed the search (as the first one is always slow).
5) search for the exact example gene symbol text.   -- browser times out.  Search for another gene symbol?  the search returns quickly!  search for ontology terms, etc...returns quickly!
6) change the web.properties to different gene symbol as example text for quicksearch (with no extra e.g, etc... again)
7) re-run the index using -Daction=create-search-index
8) re-release the webapp using the ant target
9) re-seed the search (as the first one is always slow).
10) search for the new exact example text.   -- browser times out.  Search for the old problematic gene symbol?  Search returns quickly!  -- all other text searches return quickly! 
11) take out all example text from web.properties for quicksearch. 
12) re-run the index  using -Daction=create-search-index
13) re-release the webapp using the ant target
14) re-seed the search (as the first one is always slow).
15) search for both problematic gene symbols?  search returns quickly!  all other text searches return quickly.

**Comment by yochannah** [comment]
closing this issue on the assumption it's been opened against intermine/intermine
